# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@graphile-contrib/pg-simplify-inflector-5.0.0-beta.1" = {
      name = "_at_graphile-contrib_slash_pg-simplify-inflector";
      packageName = "@graphile-contrib/pg-simplify-inflector";
      version = "5.0.0-beta.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@graphile-contrib/pg-simplify-inflector/-/pg-simplify-inflector-5.0.0-beta.1.tgz";
        sha512 = "oE1znqxBgGl6WK7t8sO4okQEqlP+GZ7ZYT4m2EB38GGbT3YuzjHTI8TcxJtDZsLPG3kPvZvB4Uc34Kb0/NGUVQ==";
      };
    };
    "@types/accepts-1.3.5" = {
      name = "_at_types_slash_accepts";
      packageName = "@types/accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/accepts/-/accepts-1.3.5.tgz";
        sha512 = "jOdnI/3qTpHABjM5cx1Hc0sKsPoYCp+DP/GJRGtDlPd7fiV9oXGGIcjW/ZOxLIvjGz8MA+uMZI9metHlgqbgwQ==";
      };
    };
    "@types/body-parser-1.17.0" = {
      name = "_at_types_slash_body-parser";
      packageName = "@types/body-parser";
      version = "1.17.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/body-parser/-/body-parser-1.17.0.tgz";
        sha512 = "a2+YeUjPkztKJu5aIF2yArYFQQp8d51wZ7DavSHjFuY1mqVgidGyzEQ41JIVNy82fXj8yPgy2vJmfIywgESW6w==";
      };
    };
    "@types/connect-3.4.32" = {
      name = "_at_types_slash_connect";
      packageName = "@types/connect";
      version = "3.4.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/connect/-/connect-3.4.32.tgz";
        sha512 = "4r8qa0quOvh7lGD0pre62CAb1oni1OO6ecJLGCezTmhQ8Fz50Arx9RUszryR8KlgK6avuSXvviL6yWyViQABOg==";
      };
    };
    "@types/cookies-0.7.1" = {
      name = "_at_types_slash_cookies";
      packageName = "@types/cookies";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cookies/-/cookies-0.7.1.tgz";
        sha512 = "ku6IvbucEyuC6i4zAVK/KnuzWNXdbFd1HkXlNLg/zhWDGTtQT5VhumiPruB/BHW34PWVFwyfwGftDQHfWNxu3Q==";
      };
    };
    "@types/express-4.16.1" = {
      name = "_at_types_slash_express";
      packageName = "@types/express";
      version = "4.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express/-/express-4.16.1.tgz";
        sha512 = "V0clmJow23WeyblmACoxbHBu2JKlE5TiIme6Lem14FnPW9gsttyHtk6wq7njcdIWH1njAaFgR8gW09lgY98gQg==";
      };
    };
    "@types/express-serve-static-core-4.16.2" = {
      name = "_at_types_slash_express-serve-static-core";
      packageName = "@types/express-serve-static-core";
      version = "4.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.16.2.tgz";
        sha512 = "qgc8tjnDrc789rAQed8NoiFLV5VGcItA4yWNFphqGU0RcuuQngD00g3LHhWIK3HQ2XeDgVCmlNPDlqi3fWBHnQ==";
      };
    };
    "@types/graphql-14.2.0" = {
      name = "_at_types_slash_graphql";
      packageName = "@types/graphql";
      version = "14.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/graphql/-/graphql-14.2.0.tgz";
        sha512 = "lELg5m6eBOmATWyCZl8qULEOvnPIUG6B443yXKj930glXIgwQirIBPp5rthP2amJW0YSzUg2s5sfgba4mRRCNw==";
      };
    };
    "@types/http-assert-1.4.0" = {
      name = "_at_types_slash_http-assert";
      packageName = "@types/http-assert";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-assert/-/http-assert-1.4.0.tgz";
        sha512 = "TZDqvFW4nQwL9DVSNJIJu4lPLttKgzRF58COa7Vs42Ki/MrhIqUbeIw0MWn4kGLiZLXB7oCBibm7nkSjPkzfKQ==";
      };
    };
    "@types/jsonwebtoken-7.2.0" = {
      name = "_at_types_slash_jsonwebtoken";
      packageName = "@types/jsonwebtoken";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/jsonwebtoken/-/jsonwebtoken-7.2.0.tgz";
        sha1 = "0fed32c8501da80ac9839d2d403a65c83d776ffd";
      };
    };
    "@types/keygrip-1.0.1" = {
      name = "_at_types_slash_keygrip";
      packageName = "@types/keygrip";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/keygrip/-/keygrip-1.0.1.tgz";
        sha1 = "ff540462d2fb4d0a88441ceaf27d287b01c3d878";
      };
    };
    "@types/koa-2.0.48" = {
      name = "_at_types_slash_koa";
      packageName = "@types/koa";
      version = "2.0.48";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa/-/koa-2.0.48.tgz";
        sha512 = "CiIUYhHlOFJhSCTmsFoFkV2t9ij1JwW26nt0W9XZoWTvmAw6zTE0+k3IAoGICtjzIfhZpZcO323NHmI1LGmdDw==";
      };
    };
    "@types/koa-compose-3.2.3" = {
      name = "_at_types_slash_koa-compose";
      packageName = "@types/koa-compose";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa-compose/-/koa-compose-3.2.3.tgz";
        sha512 = "kXvR0DPyZ3gaFxZs4WycA8lpzlPGtFmwdbgce+NWd+TG3PycPO3o5FkePH60HoBPd8BBaSiw3vhtgM42O2kQcg==";
      };
    };
    "@types/mime-2.0.1" = {
      name = "_at_types_slash_mime";
      packageName = "@types/mime";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mime/-/mime-2.0.1.tgz";
        sha512 = "FwI9gX75FgVBJ7ywgnq/P7tw+/o1GUbtP0KzbtusLigAOgIgNISRK0ZPl4qertvXSIE8YbsVJueQ90cDt9YYyw==";
      };
    };
    "@types/node-11.12.2" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "11.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-11.12.2.tgz";
        sha512 = "c82MtnqWB/CqqK7/zit74Ob8H1dBdV7bK+BcErwtXbe0+nUGkgzq5NTDmRW/pAv2lFtmeNmW95b0zK2hxpeklg==";
      };
    };
    "@types/pg-7.4.14" = {
      name = "_at_types_slash_pg";
      packageName = "@types/pg";
      version = "7.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pg/-/pg-7.4.14.tgz";
        sha512 = "2e4XapP9V/X42IGByC5IHzCzHqLLCNJid8iZBbkk6lkaDMvli8Rk62YE9wjGcLD5Qr5Zaw1ShkQyXy91PI8C0Q==";
      };
    };
    "@types/pg-types-1.11.4" = {
      name = "_at_types_slash_pg-types";
      packageName = "@types/pg-types";
      version = "1.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pg-types/-/pg-types-1.11.4.tgz";
        sha512 = "WdIiQmE347LGc1Vq3Ki8sk3iyCuLgnccqVzgxek6gEHp2H0p3MQ3jniIHt+bRODXKju4kNQ+mp53lmP5+/9moQ==";
      };
    };
    "@types/range-parser-1.2.3" = {
      name = "_at_types_slash_range-parser";
      packageName = "@types/range-parser";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/range-parser/-/range-parser-1.2.3.tgz";
        sha512 = "ewFXqrQHlFsgc09MK5jP5iR7vumV/BYayNC6PgJO2LPe8vrnNFyjQjSppfEngITi0qvfKtzFvgKymGheFM9UOA==";
      };
    };
    "@types/serve-static-1.13.2" = {
      name = "_at_types_slash_serve-static";
      packageName = "@types/serve-static";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/serve-static/-/serve-static-1.13.2.tgz";
        sha512 = "/BZ4QRLpH/bNYgZgwhKEh+5AsboDBcUdlBYgzoLX0fpj3Y2gp6EApyOlM3bK53wQS/OE1SrdSYBAbux2D1528Q==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "body-parser-1.18.3" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz";
        sha1 = "5b292198ffdd553b3a0f20ded0592b956955c8b4";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "buffer-writer-2.0.0" = {
      name = "buffer-writer";
      packageName = "buffer-writer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-writer/-/buffer-writer-2.0.0.tgz";
        sha512 = "a7ZpuTZU1TRtnwyCNW3I5dc0wWNC3VR9S++Ewyk2HHZdrO3CQJqSpd+95Us590V6AL7JqUAH2IwZ/398PmNFgw==";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "commander-2.19.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.19.0.tgz";
        sha512 = "6tvAOO+D6OENvRAh524Dh9jcfKTYDQAqvqezbCW82xj5X0pSrcpxtvRKHLG0yBY6SD7PSDrJaj+0AiOcKVd1Xg==";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "finalhandler-1.1.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz";
        sha512 = "Y1GUDo39ez4aHAw7MysnUD5JzYX+WaIj8I57kO3aEPT1fFRL4sr7mjei97FgnwhAyyzRYmQZaTHb2+9uZ1dPtg==";
      };
    };
    "graphile-build-4.3.1" = {
      name = "graphile-build";
      packageName = "graphile-build";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphile-build/-/graphile-build-4.3.1.tgz";
        sha512 = "o++JK8CSlLwt1eVDqPpv/hTDiql1kx5HheMfskmLr7MfRt3yObp4b09ceHDOFx/Aj9o+NvbPKbWnvHE8zhE+Eg==";
      };
    };
    "graphile-build-pg-4.3.1" = {
      name = "graphile-build-pg";
      packageName = "graphile-build-pg";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphile-build-pg/-/graphile-build-pg-4.3.1.tgz";
        sha512 = "2Sr34q0Q2h3E0JzQjLI3lYVWfDxoGsZzfw6zpwTkkTovm/5trNPhVOjut/d/ath7eIYWcDHQ70OO97TifLjyDA==";
      };
    };
    "graphql-14.2.0" = {
      name = "graphql";
      packageName = "graphql";
      version = "14.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql/-/graphql-14.2.0.tgz";
        sha512 = "dlFHRtxsL4sBy1C1e3v64IUd5ndZhAOHZ/z3Dr4Nm6+cvr9elrnz4BhMF9h9mRBBnhUCGLc4GH4xvPbKG6sUeA==";
      };
    };
    "graphql-iso-date-3.6.1" = {
      name = "graphql-iso-date";
      packageName = "graphql-iso-date";
      version = "3.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-iso-date/-/graphql-iso-date-3.6.1.tgz";
        sha512 = "AwFGIuYMJQXOEAgRlJlFL4H1ncFM8n8XmoVDTNypNOZyQ8LFDG2ppMFlsS862BSTCDcSUfHp8PD3/uJhv7t59Q==";
      };
    };
    "graphql-parse-resolve-info-4.1.0" = {
      name = "graphql-parse-resolve-info";
      packageName = "graphql-parse-resolve-info";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphql-parse-resolve-info/-/graphql-parse-resolve-info-4.1.0.tgz";
        sha512 = "qDRgykBm1rbyGAlduPuGtKXHlZtUcNgM8Rg6C/gDVcLww9vNV6h0nmCulpYYPWzATnAVGV8ISnLUDFCU9Y+qcA==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-errors-1.7.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.2.tgz";
        sha512 = "uUQBt3H/cSIVfch6i1EuPNy/YsRSOUBXTVfZ+yR7Zjez3qjBz6i9+i4zjNaoqcoFVI4lQJ5plg63TvGfRSDCRg==";
      };
    };
    "iconv-lite-0.4.23" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.23.tgz";
        sha512 = "neyTUVFtahjf0mB3dZT77u+8O0QB89jFdnBkd5P1JgYPbPaia3gXXOVL2fq8VyU2gMMD7SaN7QukTB/pmXYvDA==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "iterall-1.2.2" = {
      name = "iterall";
      packageName = "iterall";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/iterall/-/iterall-1.2.2.tgz";
        sha512 = "yynBb1g+RFUPY64fTrFv7nsjRrENBQJaX2UL+2Szc9REFrSNm1rpSXHGzhmAy7a9uv3vlvgBlXnf9RqmPH1/DA==";
      };
    };
    "jsonwebtoken-8.5.1" = {
      name = "jsonwebtoken";
      packageName = "jsonwebtoken";
      version = "8.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonwebtoken/-/jsonwebtoken-8.5.1.tgz";
        sha512 = "XjwVfRS6jTMsqYs0EsuJ4LGxXV14zQybNd4L2r0UvbVnSF9Af8x7p5MzbJ90Ioz/9TI41/hTCvznF/loiSzn8w==";
      };
    };
    "jwa-1.4.1" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.4.1.tgz";
        sha512 = "qiLX/xhEEFKUAJ6FiBMbes3w9ATzyk5W7Hvzpa/SLYdxNtng+gcurvrI7TbACjIXlsJyr05/S1oUhZrc63evQA==";
      };
    };
    "jws-3.2.2" = {
      name = "jws";
      packageName = "jws";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.2.2.tgz";
        sha512 = "YHlZCB6lMTllWDtSPHz/ZXTsi8S00usEV6v1tjq8tOUZzw7DpSDWVXjXDre6ed1w/pd495ODpHZYSdkRTsa0HA==";
      };
    };
    "lodash-4.17.11" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz";
        sha512 = "cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==";
      };
    };
    "lodash.includes-4.3.0" = {
      name = "lodash.includes";
      packageName = "lodash.includes";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.includes/-/lodash.includes-4.3.0.tgz";
        sha1 = "60bb98a87cb923c68ca1e51325483314849f553f";
      };
    };
    "lodash.isboolean-3.0.3" = {
      name = "lodash.isboolean";
      packageName = "lodash.isboolean";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isboolean/-/lodash.isboolean-3.0.3.tgz";
        sha1 = "6c2e171db2a257cd96802fd43b01b20d5f5870f6";
      };
    };
    "lodash.isinteger-4.0.4" = {
      name = "lodash.isinteger";
      packageName = "lodash.isinteger";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isinteger/-/lodash.isinteger-4.0.4.tgz";
        sha1 = "619c0af3d03f8b04c31f5882840b77b11cd68343";
      };
    };
    "lodash.isnumber-3.0.3" = {
      name = "lodash.isnumber";
      packageName = "lodash.isnumber";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isnumber/-/lodash.isnumber-3.0.3.tgz";
        sha1 = "3ce76810c5928d03352301ac287317f11c0b1ffc";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.once-4.1.1" = {
      name = "lodash.once";
      packageName = "lodash.once";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.once/-/lodash.once-4.1.1.tgz";
        sha1 = "0dd3971213c7c56df880977d504c88fb471a97ac";
      };
    };
    "lru-cache-4.1.5" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.5.tgz";
        sha512 = "sWZlbEP2OsHNkXrMl5GYk/jKk70MBng6UU4YI/qGDYbgf6YbP4EvmqISbXCoJiRKs+1bSpFHVgQxvJ17F2li5g==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "mime-db-1.38.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.38.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.38.0.tgz";
        sha512 = "bqVioMFFzc2awcdJZIzR3HjZFX20QhilVS7hytkKrv7xFAn8bM1gzc/FOX2awLISvWe0PV8ptFKcon+wZ5qYkg==";
      };
    };
    "mime-types-2.1.22" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.22.tgz";
        sha512 = "aGl6TZGnhm/li6F7yx82bJiBZwgiEa4Hf6CNr8YO+r5UHr53tSTYZb102zyU50DOWWKeOv0uQLRL0/9EiKWCog==";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "packet-reader-1.0.0" = {
      name = "packet-reader";
      packageName = "packet-reader";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/packet-reader/-/packet-reader-1.0.0.tgz";
        sha512 = "HAKu/fG3HpHFO0AA8WE8q2g+gBJaZ9MG7fcKk+IJPLTGAD6Psw4443l+9DGRbOIh3/aXr7Phy0TjilYivJo5XQ==";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "pg-7.9.0" = {
      name = "pg";
      packageName = "pg";
      version = "7.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg/-/pg-7.9.0.tgz";
        sha512 = "GkzteBFpsIoIBCSuomqik3IGvhqAtTr32jclR24RmUg170Jrn6ypwR97YalFHrsE1iaW8T0aAH13dmij8QUQ0g==";
      };
    };
    "pg-connection-string-0.1.3" = {
      name = "pg-connection-string";
      packageName = "pg-connection-string";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-connection-string/-/pg-connection-string-0.1.3.tgz";
        sha1 = "da1847b20940e42ee1492beaf65d49d91b245df7";
      };
    };
    "pg-int8-1.0.1" = {
      name = "pg-int8";
      packageName = "pg-int8";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-int8/-/pg-int8-1.0.1.tgz";
        sha512 = "WCtabS6t3c8SkpDBUlb1kjOs7l66xsGdKpIPZsg4wR+B3+u9UAum2odSsF9tnvxg80h4ZxLWMy4pRjOsFIqQpw==";
      };
    };
    "pg-pool-2.0.6" = {
      name = "pg-pool";
      packageName = "pg-pool";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-pool/-/pg-pool-2.0.6.tgz";
        sha512 = "hod2zYQxM8Gt482q+qONGTYcg/qVcV32VHVPtktbBJs0us3Dj7xibISw0BAAXVMCzt8A/jhfJvpZaxUlqtqs0g==";
      };
    };
    "pg-sql2-2.2.1" = {
      name = "pg-sql2";
      packageName = "pg-sql2";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-sql2/-/pg-sql2-2.2.1.tgz";
        sha512 = "S4XyLvUJv/rUMNk4+4LuT7S/aWKlQifi6ekHeshNWn0FZJxq5t4qw2VzCfbTNM3mQN7c9B6rM01FcnbRI37Y2Q==";
      };
    };
    "pg-types-2.0.0" = {
      name = "pg-types";
      packageName = "pg-types";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pg-types/-/pg-types-2.0.0.tgz";
        sha512 = "THUD7gQll5tys+5eQ8Rvs7DjHiIC3bLqixk3gMN9Hu8UrCBAOjf35FoI39rTGGc3lM2HU/R+Knpxvd11mCwOMA==";
      };
    };
    "pgpass-1.0.2" = {
      name = "pgpass";
      packageName = "pgpass";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pgpass/-/pgpass-1.0.2.tgz";
        sha1 = "2a7bb41b6065b67907e91da1b07c1847c877b306";
      };
    };
    "pluralize-7.0.0" = {
      name = "pluralize";
      packageName = "pluralize";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pluralize/-/pluralize-7.0.0.tgz";
        sha512 = "ARhBOdzS3e41FbkW/XWrTEtukqqLoK5+Z/4UeDaLuSW+39JPeFgs4gCGqsrJHVZX0fUrx//4OF0K1CUGwlIFow==";
      };
    };
    "postgraphile-4.3.3" = {
      name = "postgraphile";
      packageName = "postgraphile";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgraphile/-/postgraphile-4.3.3.tgz";
        sha512 = "Ji1zHJoLoIZFJwknjkdjIFQ2Scwn5iLaFdcgYGzSicFW54oJCOdE/XyCjkbhTHyPh93Q3KQlKTlP8h6Wd6vQVQ==";
      };
    };
    "postgraphile-core-4.3.1" = {
      name = "postgraphile-core";
      packageName = "postgraphile-core";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgraphile-core/-/postgraphile-core-4.3.1.tgz";
        sha512 = "Alp0Zt6bBQSIgvHtKzKnTWA+EOM4DwVVniRCbGJYE5AQqP1AEQ0DA8zcc4yBZFAo8RCKW86BtnO2dUV2s0728g==";
      };
    };
    "postgres-array-2.0.0" = {
      name = "postgres-array";
      packageName = "postgres-array";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-array/-/postgres-array-2.0.0.tgz";
        sha512 = "VpZrUqU5A69eQyW2c5CA1jtLecCsN2U/bD6VilrFDWq5+5UIEVO7nazS3TEcHf1zuPYO/sqGvUvW62g86RXZuA==";
      };
    };
    "postgres-bytea-1.0.0" = {
      name = "postgres-bytea";
      packageName = "postgres-bytea";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-bytea/-/postgres-bytea-1.0.0.tgz";
        sha1 = "027b533c0aa890e26d172d47cf9ccecc521acd35";
      };
    };
    "postgres-date-1.0.3" = {
      name = "postgres-date";
      packageName = "postgres-date";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-date/-/postgres-date-1.0.3.tgz";
        sha1 = "e2d89702efdb258ff9d9cee0fe91bd06975257a8";
      };
    };
    "postgres-interval-1.2.0" = {
      name = "postgres-interval";
      packageName = "postgres-interval";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postgres-interval/-/postgres-interval-1.2.0.tgz";
        sha512 = "9ZhXKM/rw350N1ovuWHbGxnGh/SNJ4cnxHiM0rxE4VN41wsg8P8zWn9hv/buK00RP4WvlOyr/RBDiptyxVbkZQ==";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "raw-body-2.3.3" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.3.tgz";
        sha512 = "9esiElv1BrZoI3rCDuOuKCBRbuApGGaDPQfjSflGxdy4oyzqghxu6klEkkVIvBje+FF0BX9coEv8KqW6X/7njw==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "semver-4.3.2" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.2.tgz";
        sha1 = "c7a07158a80bedd052355b770d82d6640f803be7";
      };
    };
    "semver-5.7.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.0.tgz";
        sha512 = "Ya52jSX2u7QKghxeoFGpLwCtGlt7j0oY9DYb5apt9nPlJ42ID+ulTXESnt/qAQcoSERyZ5sl3LDIOw0nAn/5DA==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "setprototypeof-1.1.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz";
        sha512 = "JvdAWfbXeIGaZ9cILp38HntZSFSo3mWg6xGcJJsd+d4aRMOqauag1C63dJfDw7OaMYwEbHMOxEZ1lqVRYP2OAw==";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "tslib-1.9.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.9.3.tgz";
        sha512 = "4krF8scpejhaOgqzBEcGM7yDIEfi0/8+8zDRZhNZZ2kjmHJ4hv3zCbQWxoJGz1iw5U0Jl0nma13xzHXcncMavQ==";
      };
    };
    "type-is-1.6.16" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz";
        sha512 = "HRkVv/5qY2G6I8iab9cI7v1bOIdhm94dVjQCPFElW9W+3GeDOSHmy2EBYe4VTApuzolPcmgFTN3ftVJRKR2J9Q==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
  };
  args = {
    name = "cfp";
    packageName = "cfp";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@graphile-contrib/pg-simplify-inflector-5.0.0-beta.1"
      sources."@types/accepts-1.3.5"
      sources."@types/body-parser-1.17.0"
      sources."@types/connect-3.4.32"
      sources."@types/cookies-0.7.1"
      sources."@types/express-4.16.1"
      sources."@types/express-serve-static-core-4.16.2"
      sources."@types/graphql-14.2.0"
      sources."@types/http-assert-1.4.0"
      sources."@types/jsonwebtoken-7.2.0"
      sources."@types/keygrip-1.0.1"
      sources."@types/koa-2.0.48"
      sources."@types/koa-compose-3.2.3"
      sources."@types/mime-2.0.1"
      sources."@types/node-11.12.2"
      sources."@types/pg-7.4.14"
      sources."@types/pg-types-1.11.4"
      sources."@types/range-parser-1.2.3"
      sources."@types/serve-static-1.13.2"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      (sources."body-parser-1.18.3" // {
        dependencies = [
          sources."http-errors-1.6.3"
        ];
      })
      sources."buffer-equal-constant-time-1.0.1"
      sources."buffer-writer-2.0.0"
      sources."bytes-3.0.0"
      sources."chalk-1.1.3"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-2.19.0"
      sources."content-type-1.0.4"
      sources."debug-2.6.9"
      sources."depd-1.1.2"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."escape-string-regexp-1.0.5"
      (sources."finalhandler-1.1.1" // {
        dependencies = [
          sources."statuses-1.4.0"
        ];
      })
      (sources."graphile-build-4.3.1" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.2"
          sources."supports-color-5.5.0"
        ];
      })
      (sources."graphile-build-pg-4.3.1" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.2"
          sources."supports-color-5.5.0"
        ];
      })
      sources."graphql-14.2.0"
      sources."graphql-iso-date-3.6.1"
      sources."graphql-parse-resolve-info-4.1.0"
      sources."has-ansi-2.0.0"
      sources."has-flag-3.0.0"
      (sources."http-errors-1.7.2" // {
        dependencies = [
          sources."setprototypeof-1.1.1"
        ];
      })
      sources."iconv-lite-0.4.23"
      sources."inherits-2.0.3"
      sources."iterall-1.2.2"
      (sources."jsonwebtoken-8.5.1" // {
        dependencies = [
          sources."ms-2.1.1"
        ];
      })
      sources."jwa-1.4.1"
      sources."jws-3.2.2"
      sources."lodash-4.17.11"
      sources."lodash.includes-4.3.0"
      sources."lodash.isboolean-3.0.3"
      sources."lodash.isinteger-4.0.4"
      sources."lodash.isnumber-3.0.3"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.once-4.1.1"
      sources."lru-cache-4.1.5"
      sources."media-typer-0.3.0"
      sources."mime-db-1.38.0"
      sources."mime-types-2.1.22"
      sources."moment-2.24.0"
      sources."ms-2.0.0"
      sources."on-finished-2.3.0"
      sources."packet-reader-1.0.0"
      sources."parseurl-1.3.2"
      (sources."pg-7.9.0" // {
        dependencies = [
          sources."semver-4.3.2"
        ];
      })
      sources."pg-connection-string-0.1.3"
      sources."pg-int8-1.0.1"
      sources."pg-pool-2.0.6"
      sources."pg-sql2-2.2.1"
      sources."pg-types-2.0.0"
      sources."pgpass-1.0.2"
      sources."pluralize-7.0.0"
      sources."postgraphile-4.3.3"
      sources."postgraphile-core-4.3.1"
      sources."postgres-array-2.0.0"
      sources."postgres-bytea-1.0.0"
      sources."postgres-date-1.0.3"
      sources."postgres-interval-1.2.0"
      sources."pseudomap-1.0.2"
      sources."qs-6.5.2"
      (sources."raw-body-2.3.3" // {
        dependencies = [
          sources."http-errors-1.6.3"
        ];
      })
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."semver-5.7.0"
      sources."setprototypeof-1.1.0"
      sources."split-1.0.1"
      sources."statuses-1.5.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."through-2.3.8"
      sources."toidentifier-1.0.0"
      sources."tslib-1.9.3"
      sources."type-is-1.6.16"
      sources."unpipe-1.0.0"
      sources."xtend-4.0.1"
      sources."yallist-2.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "CFP management for elm-conf";
      homepage = "https://github.com/elm-conf/cfp#readme";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}