-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (CreateUserRequiredArguments, CurrentUserIsReviewerRequiredArguments, DeleteUserByIdRequiredArguments, DeleteUserRequiredArguments, RegisterRequiredArguments, UpdateUserByIdRequiredArguments, UpdateUserRequiredArguments, createUser, currentUserIsReviewer, deleteUser, deleteUserById, register, updateUser, updateUserById)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateUserRequiredArguments =
    { input : Api.InputObject.CreateUserInput }


{-| Creates a single `User`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createUser : CreateUserRequiredArguments -> SelectionSet decodesTo Api.Object.CreateUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
createUser requiredArgs object_ =
    Object.selectionForCompositeField "createUser" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeCreateUserInput ] object_ (identity >> Decode.nullable)


type alias UpdateUserRequiredArguments =
    { input : Api.InputObject.UpdateUserInput }


{-| Updates a single `User` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUser : UpdateUserRequiredArguments -> SelectionSet decodesTo Api.Object.UpdateUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateUser requiredArgs object_ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeUpdateUserInput ] object_ (identity >> Decode.nullable)


type alias UpdateUserByIdRequiredArguments =
    { input : Api.InputObject.UpdateUserByIdInput }


{-| Updates a single `User` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateUserById : UpdateUserByIdRequiredArguments -> SelectionSet decodesTo Api.Object.UpdateUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
updateUserById requiredArgs object_ =
    Object.selectionForCompositeField "updateUserById" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeUpdateUserByIdInput ] object_ (identity >> Decode.nullable)


type alias DeleteUserRequiredArguments =
    { input : Api.InputObject.DeleteUserInput }


{-| Deletes a single `User` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUser : DeleteUserRequiredArguments -> SelectionSet decodesTo Api.Object.DeleteUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteUser requiredArgs object_ =
    Object.selectionForCompositeField "deleteUser" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeDeleteUserInput ] object_ (identity >> Decode.nullable)


type alias DeleteUserByIdRequiredArguments =
    { input : Api.InputObject.DeleteUserByIdInput }


{-| Deletes a single `User` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteUserById : DeleteUserByIdRequiredArguments -> SelectionSet decodesTo Api.Object.DeleteUserPayload -> SelectionSet (Maybe decodesTo) RootMutation
deleteUserById requiredArgs object_ =
    Object.selectionForCompositeField "deleteUserById" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeDeleteUserByIdInput ] object_ (identity >> Decode.nullable)


type alias CurrentUserIsReviewerRequiredArguments =
    { input : Api.InputObject.CurrentUserIsReviewerInput }


{-|

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
currentUserIsReviewer : CurrentUserIsReviewerRequiredArguments -> SelectionSet decodesTo Api.Object.CurrentUserIsReviewerPayload -> SelectionSet (Maybe decodesTo) RootMutation
currentUserIsReviewer requiredArgs object_ =
    Object.selectionForCompositeField "currentUserIsReviewer" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeCurrentUserIsReviewerInput ] object_ (identity >> Decode.nullable)


type alias RegisterRequiredArguments =
    { input : Api.InputObject.RegisterInput }


{-|

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
register : RegisterRequiredArguments -> SelectionSet decodesTo Api.Object.RegisterPayload -> SelectionSet (Maybe decodesTo) RootMutation
register requiredArgs object_ =
    Object.selectionForCompositeField "register" [ Argument.required "input" requiredArgs.input Api.InputObject.encodeRegisterInput ] object_ (identity >> Decode.nullable)
