-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (CreateUserPayload(..), DeleteUserPayload(..), PageInfo(..), RegisterPayload(..), UpdateUserPayload(..), User(..), UsersConnection(..), UsersEdge(..))


type CreateUserPayload
    = CreateUserPayload


type DeleteUserPayload
    = DeleteUserPayload


type PageInfo
    = PageInfo


type RegisterPayload
    = RegisterPayload


type UpdateUserPayload
    = UpdateUserPayload


type User
    = User


type UsersConnection
    = UsersConnection


type UsersEdge
    = UsersEdge
