-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (Cursor, Id, codecs)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Cursor =
    Api.Scalar.Cursor


type alias Id =
    Api.Scalar.Id


codecs : Api.Scalar.Codecs Cursor Id
codecs =
    Api.Scalar.defineCodecs
        { codecCursor = defaultCodecs.codecCursor
        , codecId = defaultCodecs.codecId
        }
